.\"
.\" sprite - ncurses-based sprite editor
.\"
.\" Copyright (c) 2020 Brian Callahan <bcallah@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 11, 2020
.Dt SPRITE 1
.Os
.Sh NAME
.Nm sprite
.Nd ncurses-based sprite editor
.Sh SYNOPSIS
.Nm
.Op Fl e
.Op Ar file
.Sh DESCRIPTION
.Nm
is an ncurses-based sprite editor.
You can use it to create and share pixel art.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl e
Use an extended canvas of 32x32 pixels instead of the default 16x16 pixels,
if the terminal is large enough to support the larger canvas.
.El
.Sh AUTHORS
.Nm
was written by
.An Brian Callahan Aq Mt bcallah@openbsd.org .
.Sh CAVEATS
Console aspect ratio may not match user expectations.
PNG export creates standard square pixels.
